mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('about', views.about_view, name='about'),

    ####### CAUSES #######
    path('causes', views.causes_view, name='causes'),
    path('cause-detail/dreams', views.cause_detail_dreams, name='cause-dreams'),
    path('cause-detail/ovc', views.cause_detail_ovc, name='cause-ovc'),
    path('cause-detail/she-leads', views.cause_detail_she_leads, name='cause-she-leads'),
    path('cause-detail/child-sponsorship', views.cause_child_sponsorship, name='child-sponsorship'),
    path('cause-detail/sustainable-livelihoods', views.cause_sustainable_livelihoods, name='sustainable-livelihoods'),
    path('cause-detail/research', views.cause_research, name='cause-research'),
    path('cause-detail/safe-water-projects', views.cause_safe_water_projects, name='cause-safe-water-projects'),
    path('cause-detail/youth-center', views.cause_youth_center, name='cause-youth-center'),
    ####### END OF CAUSES #######
    
    path('blog', views.blog_view, name='blog'),
    path('post', views.PostCreateView.as_view(template_name='mainapp/post.html'), name='write-a-post'),
    path('volunteer', views.volunteer_view, name='volunteer'),
    path('mentor', views.mentor_view, name='mentor'),
    path('impact', views.impact_view, name='impact'),
    path('gallery', views.gallery_view, name='gallery'),
    path('gallery/<str:catego>/', views.gallery_detail, name='gallery-detail'),
    path('staff', views.staff_view, name='staff'),
    path('contact', views.contact_view, name='contact'),

]

pamojaprojo/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('about', views.about_view, name='about'),

    ####### CAUSES #######
    path('causes', views.causes_view, name='causes'),
    path('cause-detail/dreams', views.cause_detail_dreams, name='cause-dreams'),
    path('cause-detail/ovc', views.cause_detail_ovc, name='cause-ovc'),
    path('cause-detail/she-leads', views.cause_detail_she_leads, name='cause-she-leads'),
    path('cause-detail/child-sponsorship', views.cause_child_sponsorship, name='child-sponsorship'),
    path('cause-detail/sustainable-livelihoods', views.cause_sustainable_livelihoods, name='sustainable-livelihoods'),
    path('cause-detail/research', views.cause_research, name='cause-research'),
    path('cause-detail/safe-water-projects', views.cause_safe_water_projects, name='cause-safe-water-projects'),
    ####### END OF CAUSES #######
    
    path('blog', views.blog_view, name='blog'),
    path('post', views.PostCreateView.as_view(template_name='mainapp/post.html'), name='write-a-post'),
    path('volunteer', views.volunteer_view, name='volunteer'),
    path('mentor', views.mentor_view, name='mentor'),
    path('impact', views.impact_view, name='impact'),
    path('gallery', views.gallery_view, name='gallery'),
    path('gallery/<str:catego>/', views.gallery_detail, name='gallery-detail'),
    path('staff', views.staff_view, name='staff'),
    path('contact', views.contact_view, name='contact'),

]

pamojaprojo/pamojaproject/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/forms.py
from django import forms
from .models import Volunteer, Mentor, ContactPage, MailList, Help_choices
from .countries import COUNTRIES

class VolunteerForm(forms.ModelForm):
    firstname = forms.CharField(widget=forms.TextInput(),label="First Name")
    lastname = forms.CharField(widget=forms.TextInput(),label="Last Name")
    email = forms.EmailField(widget=forms.EmailInput())
    country = forms.Select()
    what_can_you_help_with = forms.ModelMultipleChoiceField(queryset=Help_choices.objects.all(), widget=forms.CheckboxSelectMultiple)
    any_other_area_you_would_like_to_help = forms.CharField(widget=forms.TextInput())
    why_would_you_like_to_help = forms.CharField(widget=forms.Textarea(attrs={'rows' : "5"}))

    class Meta:
        model = Volunteer
        fields = '__all__'

class MentorForm(forms.ModelForm):
    firstname = forms.CharField(widget=forms.TextInput(), label="First Name")
    lastname = forms.CharField(widget=forms.TextInput(), label="Last Name")
    email = forms.EmailField(widget=forms.EmailInput())
    phone_number = forms.CharField(widget=forms.TextInput(), label="Phone Number", required=False)
    company = forms.CharField(widget=forms.TextInput())
    country = forms.Select()
    area_of_interest = forms.CharField(widget=forms.TextInput())
    any_other_details = forms.CharField(widget=forms.Textarea(attrs={'rows' : "5"}))

    class Meta:
        model = Mentor
        fields = '__all__'

class ContactPageForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput())
    email = forms.EmailField(widget=forms.EmailInput())
    subject = forms.CharField(widget=forms.TextInput())
    message = forms.CharField(widget=forms.Textarea(attrs={'rows' : "5"}))

    class Meta:
        model = ContactPage
        fields = '__all__'

class MailListForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput())

    class Meta:
        model = MailList
        fields = '__all__'

pamojaprojo/mainapp/forms.py
from django import forms
from .models import Volunteer, Mentor, ContactPage, MailList, Help_choices
from .countries import COUNTRIES

class VolunteerForm(forms.ModelForm):
    firstname = forms.CharField(widget=forms.TextInput())
    lastname = forms.CharField(widget=forms.TextInput())
    email = forms.EmailField(widget=forms.EmailInput())
    country = forms.Select()
    what_can_you_help_with = forms.ModelMultipleChoiceField(queryset=Help_choices.objects.all(), widget=forms.CheckboxSelectMultiple)
    any_other_area_you_would_like_to_help = forms.CharField(widget=forms.TextInput())
    why_would_you_like_to_help = forms.CharField(widget=forms.Textarea(attrs={'rows' : "5"}))

    class Meta:
        model = Volunteer
        fields = '__all__'

class MentorForm(forms.ModelForm):
    firstname = forms.CharField(widget=forms.TextInput())
    lastname = forms.CharField(widget=forms.TextInput())
    email = forms.EmailField(widget=forms.EmailInput())
    company = forms.CharField(widget=forms.TextInput())
    country = forms.Select()
    area_of_interest = forms.CharField(widget=forms.TextInput())
    any_other_details = forms.CharField(widget=forms.Textarea(attrs={'rows' : "5"}))

    class Meta:
        model = Mentor
        fields = '__all__'

class ContactPageForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput())
    email = forms.EmailField(widget=forms.EmailInput())
    subject = forms.CharField(widget=forms.TextInput())
    message = forms.CharField(widget=forms.Textarea(attrs={'rows' : "5"}))

    class Meta:
        model = ContactPage
        fields = '__all__'

class MailListForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput())

    class Meta:
        model = MailList
        fields = '__all__'

mainapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import VolunteerForm, MentorForm, MailListForm, ContactPageForm
from .models import ImageCategory, Volunteer, Post, ImageFile
from django.contrib import messages
from django.views.generic import CreateView

def home_view(request):
    if request.method == 'POST':
        form = MailListForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your email was submitted successfully')
            return redirect('mainapp:home')
    else:
        form = MailListForm()
    context = {'form':form}
    return render(request, 'mainapp/index.html', context)

def about_view(request):
    return render(request, 'mainapp/about.html')


########## Begining of Causes #############
def causes_view(request):
    return render(request, 'mainapp/causes.html')

def cause_detail_dreams(request):
    return render(request, 'mainapp/cause-dreams.html')

def cause_detail_ovc(request):
    return render(request, 'mainapp/cause-ovc.html')

def cause_child_sponsorship(request):
    return render(request, 'mainapp/cause-child-sponsorship.html')

def cause_detail_she_leads(request):
    return render(request, 'mainapp/cause-she-leads.html')

def cause_sustainable_livelihoods(request):
    return render(request, 'mainapp/cause-sustainable-livelihoods.html')

def cause_research(request):
    return render(request, 'mainapp/cause-research.html')

def cause_safe_water_projects(request):
    return render(request, 'mainapp/cause-safe-water-projects.html')

def cause_youth_center(request):
    return render(request, 'mainapp/cause-youth-center.html')




######### End of Causes ##################

def blog_view(request):
    return render(request, 'mainapp/blog.html')

def volunteer_view(request):
    if request.method == 'POST':
        form = VolunteerForm(request.POST or None)
        if form.is_valid():
            print(form)
            form.save()
            messages.success(request, 'Your details were submitted successfully')
            return redirect('mainapp:volunteer')
    else:
        form = VolunteerForm()
    context = {'form':form} 
    return render(request, 'mainapp/volunteer.html', context)

def mentor_view(request):
    if request.method == 'POST':
        form = MentorForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your details were submitted successfully')
            return redirect('mainapp:mentor')
    else:
        form = MentorForm()
    context = {'form':form}
    return render(request, 'mainapp/mentor.html', context)

def impact_view(request):
    return render(request, 'mainapp/impact.html')

def gallery_view(request):
    images = ImageFile.objects.all()
    image_categories = ImageCategory.objects.all()
    context = {'images':images, 'image_categories':image_categories}
    return render(request, 'mainapp/gallery.html', context)

def gallery_detail(request, catego):
    images = ImageFile.objects.filter(category__category_name=catego)
    context = {'images':images, 'category': catego}
    return render(request, 'mainapp/gallery-detail.html', context)

def staff_view(request):
    return render(request, 'mainapp/staff.html')

def contact_view(request):
    if request.method == 'POST':
        form = ContactPageForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your details were submitted successfully')
            return redirect('mainapp:contact')
    else:
        form = ContactPageForm()
    context = {'form':form}
    return render(request, 'mainapp/contact.html', context)

class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'content']
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('mainapp:blog')

pamojaprojo/mainapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import VolunteerForm, MentorForm, MailListForm, ContactPageForm
from .models import ImageCategory, Volunteer, Post, ImageFile
from django.contrib import messages
from django.views.generic import CreateView

def home_view(request):
    if request.method == 'POST':
        form = MailListForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your email was submitted successfully')
            return redirect('mainapp:home')
    else:
        form = MailListForm()
    context = {'form':form}
    return render(request, 'mainapp/index.html', context)

def about_view(request):
    return render(request, 'mainapp/about.html')


########## Begining of Causes #############
def causes_view(request):
    return render(request, 'mainapp/causes.html')

def cause_detail_dreams(request):
    return render(request, 'mainapp/cause-dreams.html')

def cause_detail_ovc(request):
    return render(request, 'mainapp/cause-ovc.html')

def cause_child_sponsorship(request):
    return render(request, 'mainapp/cause-child-sponsorship.html')

def cause_detail_she_leads(request):
    return render(request, 'mainapp/cause-she-leads.html')

def cause_sustainable_livelihoods(request):
    return render(request, 'mainapp/cause-sustainable-livelihoods.html')

def cause_research(request):
    return render(request, 'mainapp/cause-research.html')

def cause_safe_water_projects(request):
    return render(request, 'mainapp/cause-safe-water-projects.html')






######### End of Causes ##################

def blog_view(request):
    return render(request, 'mainapp/blog.html')

def volunteer_view(request):
    if request.method == 'POST':
        form = VolunteerForm(request.POST or None)
        if form.is_valid():
            print(form)
            form.save()
            messages.success(request, 'Your details were submitted successfully')
            return redirect('mainapp:volunteer')
    else:
        form = VolunteerForm()
    context = {'form':form} 
    return render(request, 'mainapp/volunteer.html', context)

def mentor_view(request):
    if request.method == 'POST':
        form = MentorForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your details were submitted successfully')
            return redirect('mainapp:mentor')
    else:
        form = MentorForm()
    context = {'form':form}
    return render(request, 'mainapp/mentor.html', context)

def impact_view(request):
    return render(request, 'mainapp/impact.html')

def gallery_view(request):
    images = ImageFile.objects.all()
    image_categories = ImageCategory.objects.all()
    context = {'images':images, 'image_categories':image_categories}
    return render(request, 'mainapp/gallery.html', context)

def gallery_detail(request, catego):
    images = ImageFile.objects.filter(category__category_name=catego)
    context = {'images':images, 'category': catego}
    return render(request, 'mainapp/gallery-detail.html', context)

def staff_view(request):
    return render(request, 'mainapp/staff.html')

def contact_view(request):
    if request.method == 'POST':
        form = ContactPageForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your details were submitted successfully')
            return redirect('mainapp:contact')
    else:
        form = ContactPageForm()
    context = {'form':form}
    return render(request, 'mainapp/contact.html', context)

class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'content']
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('mainapp:blog')

mainapp/templates/mainapp/cause-child-sponsorship.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Pamoja CBO</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/stuff3.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/brandonstyle.css' %}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/solid.css"
        integrity="sha384-Tv5i09RULyHKMwX0E8wJUqSOaXlyu3SQxORObAI08iUwIalMmN5L6AvlPX2LMoSE" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/fontawesome.css"
        integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous" />
    <link href="https://db.onlinewebfonts.com/c/12ca6eb8a45b8ac406fb5a09bb9daab2?family=Lyon+Display+Web+Black"
        rel="stylesheet" type="text/css" />

<style>
    .lyon {
        font-family: 'Lyon Display Web Black'
    }
    .arnhem {
        font-family: 'Arnhem Blond'
    }
/* Extra small viewport or screen */
@media (min-width: 280px) and (max-width: 480px) {
    .mobiliner{
        line-height:1.4;
    }
    .cha-1 {
        order:1;
    }
    .cha-2{
        padding-top:25px;
        order:2;
    }
}

@media only screen and (min-width : 480px) {

}
/* Small viewport or screen */
@media only screen and (min-width : 768px) {

}
/* Medium viewport or screen */
@media only screen and (min-width : 992px) {

}
/* Large viewport or screen */
@media only screen and (min-width : 1200px) {

}
</style>
    <script
        nonce="99bc3aeb-c369-4673-a964-210f658c954f">(function (w, d) { !function (a, e, t, r) { a.zarazData = a.zarazData || {}, a.zarazData.executed = [], a.zaraz = { deferred: [] }, a.zaraz.q = [], a.zaraz._f = function (e) { return function () { var t = Array.prototype.slice.call(arguments); a.zaraz.q.push({ m: e, a: t }) } }; for (const e of ["track", "set", "ecommerce", "debug"]) a.zaraz[e] = a.zaraz._f(e); a.addEventListener("DOMContentLoaded", (() => { var t = e.getElementsByTagName(r)[0], z = e.createElement(r), n = e.getElementsByTagName("title")[0]; for (n && (a.zarazData.t = e.getElementsByTagName("title")[0].text), a.zarazData.x = Math.random(), a.zarazData.w = a.screen.width, a.zarazData.h = a.screen.height, a.zarazData.j = a.innerHeight, a.zarazData.e = a.innerWidth, a.zarazData.l = a.location.href, a.zarazData.r = e.referrer, a.zarazData.k = a.screen.colorDepth, a.zarazData.n = e.characterSet, a.zarazData.o = (new Date).getTimezoneOffset(), a.zarazData.q = []; a.zaraz.q.length;) { const e = a.zaraz.q.shift(); a.zarazData.q.push(e) } z.defer = !0; for (const e of [localStorage, sessionStorage]) Object.keys(e).filter((a => a.startsWith("_zaraz_"))).forEach((t => { try { a.zarazData["z_" + t.slice(7)] = JSON.parse(e.getItem(t)) } catch { a.zarazData["z_" + t.slice(7)] = e.getItem(t) } })); z.referrerPolicy = "origin", z.src = "../../cdn-cgi/zaraz/sd0d9.js?z=" + btoa(encodeURIComponent(JSON.stringify(a.zarazData))), t.parentNode.insertBefore(z, t) })) }(w, d, 0, "script"); })(window, document);</script>
</head>

<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'mainapp:home' %}">
                <img class="img-fluid" src="{% static 'images/home/PamojaPamoja.png' %}" alt="logo"
                    style="width:180px;height:auto">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a href="{% url 'mainapp:home' %}" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="{% url 'mainapp:about' %}" class="nav-link">About Us</a></li>
                    <li class="nav-item active dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                            aria-haspopup="true" aria-expanded="false">What We Do</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'mainapp:causes' %}" style="font-size: 14px;">Causes</a>
                            <a class="dropdown-item" href="{% url 'mainapp:impact' %}" style="font-size: 14px;">Our
                                Impact</a>
                        </div>
                    </li>
                    <li class="nav-item"><a href="{% url 'mainapp:blog' %}" class="nav-link">Blog</a></li>
                    <li class="nav-item"><a href="{% url 'mainapp:volunteer' %}" class="nav-link">Volunteer</a></li>
                    <li class="nav-item"><a href="{% url 'mainapp:gallery' %}" class="nav-link">Gallery</a></li>
                    <li class="nav-item"><a href="{% url 'mainapp:contact' %}" class="nav-link">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
      <br><br><br><br><br>
      
    <div class="container" style="max-width: 1440px;">
        <div class="row align-items-center">
            <div class="col-md-1"></div>
            <div class="col-md-5">
                <!-- <h2 class="text-center"><span style="font-weight:bold">D.R.E.A.M.S.</span> - Reducing new HIV  infections and preventing GBV  among Adolescent girls and young women ages 9-24</h2> -->
                <h1 class="lyon" style="font-weight: bold;letter-spacing: 2px;font-size:29px;">Enhancing Access to Education - Child Sponsorship Project.</h1>
                <p class="text-justify">Pamoja supports school going children aged between <span style="color:red">Number here</span> by providing bursaries, uniforms, supplies and mentorship.</p>
            <br>
            </div>
            <div class="col-md-5">
                <img src="{% static 'images/dreams.png' %}" class="img-fluid">
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
      <div class="container" style="max-width:1440px">
        
        <div class="row">
    <div class="col-xl-4 order-xl-2 cha-2">
        <!-- Progress track -->
        <div class="card">
            <!-- Card header -->
            <div class="card-header">
                <!-- Title -->
                <h5 class="h3 mb-0">
                    <span style="font-weight: bold;font-family:'Lyon Display Web Black'">More Like This. </span>
                    <a href="{% url 'mainapp:causes' %}" class="btn btn-sm btn-primary"
                        style="float:right;border-radius:7px;font-weight: bold;"><span style="font-family: 'Brandon Text'!important">SEE ALL</span></a></h5>
            </div>
            <!-- Card body -->
            <div class="card-body">
                <!-- List group -->
                <ul class="list-group list-group-flush list my--3">
                    
                    <p class="text-gray display-5 mobiliner">1. <a href="{% url 'mainapp:cause-ovc' %}">Children affected/infected with HIV.</a></p>
                    <p class="text-gray display-5 mobiliner">2. <a href="{% url 'mainapp:cause-she-leads' %}">Inclusion of Girls in decision making.</a></p>
                    <p class="text-gray display-5 mobiliner">3. <a href="{% url 'mainapp:sustainable-livelihoods' %}">Sustainable Livelihoods.</a></p>
                    <p class="text-gray display-5 mobiliner">4. <a href="{% url 'mainapp:cause-safe-water-projects' %}">Safe Water Projects.</a></p>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-xl-8 order-xl-1 cha-1">
        <div class="row">
        </div>
        <div class="card">
            <div class="card-header">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h3 class="mb-0 lyon" style="font-weight: bold;">Program Details. </h3>
                    </div>
                    <div class="col-4 text-right">
                        <!--<a href="#!" class="btn btn-sm btn-primary">Settings</a>-->
                    </div>
                </div>
            </div>
            <div class="card-body">
                <p class="text-justify mobiliner"><span style="font-weight:bold">Partner: </span>Plan International Kenya</p>
                <p class="text-justify mobiliner"><span style="font-weight:bold">Target beneficiaries: </span>School going children</p>
                <p class="text-justify mobiliner"><span style="font-weight:bold">Duration: </span></p>
                <p class="text-justify mobiliner"><span style="font-weight:bold;">Objective: </p>
                
                <p class="text-justify mobiliner"><span style="font-weight:bold;">Key Accomplishments: </span></p>
                <p class="text-justify mobiliner">This project serves 2,600 children. It offers various support to the beneficiaries including school levy, school supplies and early childhood development education support</p>
                <!-- <p class="text-justify">For <strong>Number Here</strong> USD, you can support lobby and advocacy exercises for girls who need and facilitate referrals and linkages to requisite support groups.</p>
                <p class="text-justify"><strong>Stakeholders:</strong></p>
                <p class="text-justify">Targeting government - Policy issues - Inclusion and meaningful participation of GYW</p>
                <p class="text-justify">Civil Society organizations with the aim of creating space for GYW</p>
                <p class="text-justify">Communities - Discriminative practices that hinder participation of girls and young women</p>
                <p class="text-justify">Strengthening linkages - Partner for direct services - sanitary, fee(all levels), leadership training & coaching facilitation</p>
                <p class="text-justify">Fascinating facts:</p>
                <p class="text-justify">Lobbying and advocacy - Challenging norms - the things the community values most - reception among boys and men indicates lack of readiness to let go of norms</p>
                <p class="text-justify">Girls have demonstrated interest and enthusiasm in taking lead in advocating against issues affecting upon completion of the sensitization program</p>
                <p class="text-justify">Girls are more aware and conscious of their lobbying spaces and their role in engaging the community in forward facing discussion aimed at their wellbeing.</p> -->
            </div>
        </div>
    </div>
</div>
      </div>


<br><br><br>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script
  src="{% static 'js/jquery-migrate-3.0.1.min.js%2bpopper.min.js%2bbootstrap.min.js%2bjquery.easing.1.3.js.pagespeed.jc.UfoK2ZK92N.js' %}"></script>
<script>eval(mod_pagespeed__5Yoqz5Pwn);</script>
<script>eval(mod_pagespeed_KZlkIIJlO3);</script>
<script>eval(mod_pagespeed_QWr0uXaXaU);</script>
<script>eval(mod_pagespeed_pnj9KVQygE);</script>
<script
  src="{% static 'js/jquery.waypoints.min.js%2bjquery.stellar.min.js%2bowl.carousel.min.js%2bjquery.magnific-popup.min.js.pagespeed.jc.CE0oN1Bwzq.js' %}"></script>
<script>eval(mod_pagespeed_6t$u8$1XBS);</script>
<script>eval(mod_pagespeed_YhLXOfd9vP);</script>
<script>eval(mod_pagespeed_xdKIJPVMXB);</script>
<script>eval(mod_pagespeed_hFobBDlaRU);</script>
<script src="js/bootstrap-datepicker.js"></script>
<script
  src="{% static 'js/jquery.fancybox.min.js%2baos.js%2bjquery.animateNumber.min.js%2bgoogle-map.js%2bmain.js.pagespeed.jc.nGnVN_nqcj.js' %}"></script>
<script>eval(mod_pagespeed_bPMfuRRc$t);</script>
<script>eval(mod_pagespeed_327Vziik2k);</script>
<script>eval(mod_pagespeed_dFb3UKP9Kq);</script>
<script
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
<script>eval(mod_pagespeed_c7BIxLN_4h);</script>
<script>eval(mod_pagespeed_HdekMp55Bh);</script>

</body>

<!-- Mirrored from preview.colorlib.com/theme/givehope/ by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 31 May 2022 13:09:47 GMT -->

</html>